application: ningsync
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
  login: required


- url: /blogs/admin/.*
  script: blogs.py
  login: required

- url: /blogs/.*
  script: blogs.py
  login: admin


- url: /auth/admin/.*
  script: auth.py
  login: required


- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico


- url: /.*
  static_files: templates/errors/404.html
  upload: templates/errors/404.html


error_handlers:
- file: templates/errors/default.html
